#!/usr/bin/with-contenv bash

# Set default PostgreSQL version
PGVERSION=${PG_VERSION:-14}

# for ubuntu
export PATH=$PATH:/usr/lib/postgresql/${PGVERSION}/bin/

# Check if trying to upgrade PostgreSQL version
if [ -f /config/postgres/PG_VERSION ] && [ $(cat /config/postgres/PG_VERSION) != ${PGVERSION} ]; then
	echo "Looks like you are trying to upgrade to PostgreSQL $PGVERSION, this will cause corruption and is not supported."
	echo "You may want to consider using the 'pg_upgrade' utility to upgrade your $(cat /config/postgres/PG_VERSION) to ${PGVERSION},"
	echo "otherwise stick with $(cat /config/postgres/PG_VERSION) by setting 'PG_VERSION' back to '$(cat /config/postgres/PG_VERSION)'"
	sleep infinity
fi

# Create postgres folders and set permissions
mkdir -p \
	/config/postgres/ \
	/run/postgresql/
chown -R postgres:postgres \
	/config/postgres/ \
	/run/postgresql/

# Initialize PostgreSQL database if not already initialized
if [ ! -f /config/postgres/PG_VERSION ]; then
	echo "Initializing PostgreSQL Database"
	s6-setuidgid postgres initdb -D /config/postgres/ --username=postgres
	s6-setuidgid postgres pg_ctl -D /config/postgres/ -o '-c listen_addresses= -p 5432' -w start
	s6-setuidgid postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
	s6-setuidgid postgres pg_ctl -D /config/postgres/ -m fast -w stop
else
	echo "PostgreSQL Database Already Initialised"
fi
