#!/usr/bin/with-contenv bash

# PostgreSQL 15 with pgvecto-rs extension
PGVERSION=15

# for ubuntu
export PATH=$PATH:/usr/lib/postgresql/${PGVERSION}/bin/

exec s6-setuidgid postgres \
	pg_ctl -D /config/postgres/ \
	-m fast -w stop
