#!/usr/bin/with-contenv bash

# PostgreSQL 14 with VectorChord extension (Immich official image)
PGVERSION=14

# for ubuntu
export PATH=$PATH:/usr/lib/postgresql/${PGVERSION}/bin/

exec s6-setuidgid postgres \
	pg_ctl -D /config/postgres/ \
	-m fast -w stop
