#!/usr/bin/with-contenv bash

# Set default PostgreSQL version
PGVERSION=${PG_VERSION:-14}

# for ubuntu
export PATH=$PATH:/usr/lib/postgresql/${PGVERSION}/bin/

exec s6-setuidgid postgres \
	pg_ctl -D /config/postgres/ \
	-m fast -w stop
